apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HazemFelhi/argocd-conf.git
    targetRevision: HEAD
    path: deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: coffee-shop
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
  # template:
  #   spec:
  #     serviceAccountName: serviceaccout-ingress

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-aconfig-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HazemFelhi/argocd-conf.git
    targetRevision: HEAD
    path: config-server-deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: coffee-shop
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-ms-categorie
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HazemFelhi/argocd-conf.git
    targetRevision: HEAD
    path: categorie-deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: coffee-shop
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HazemFelhi/argocd-conf.git
    targetRevision: HEAD
    path: postgresql-deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: coffee-shop
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: argocd
spec:
  project: default
  source:
    chart: adwerx/awx
    repoURL: https://github.com/AdWerx/charts/tree/master/awx
    targetRevision: master
    path: awx
    helm:
      releaseName: adwerx/awx
      parameters:
      - name: "service.type"
        value: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true