apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-shop
spec:
  selector:
    matchLabels:
      app: coffee-shop
  replicas: 2
  template:
    metadata:
      labels:
        app: coffee-shop
    spec:
      containers:
      - name: coffee-shop
        image: docker.io/hazemfelhi/cf:latest #docker.io/moohamedd/angular-app:v1 
        ports:
        - containerPort: 9090
