#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
  #name: microservice-ingress
  #annotations:
    #kubernetes.io/ingress.class: traefik
# spec:
#   rules:
#     - host: microservice.eureka.com
#       http:
#         paths:
#           #- path:
#             #pathType: Prefix
#             backend:
#               service:
#                 name: eureka-server-service
#                 port:
#                   number: 80
# ---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: coffee-shop
  annotations:
    app.kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: ingress-nginx.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: eureka-server-service
              port:
                number: 8761

