apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
spec:
  selector:
    app: eureka-server
  #type: NodePort
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
    #nodePort: 30155

  
