apiVersion: v1
kind: Service
metadata:
  name: coffee-shop-service
spec:
  selector:
    app: coffee-shop
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30150

  
