# Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  ports:
    - protocol: "TCP"
      port: 80    # Port inside the cluster
      protocol: TCP
      targetPort: 80
  selector:
    app: front