apiVersion: argoproj.io/v1alpha1
kind: Rollout #Deployment
metadata:
  name: ms-categorie
spec:
  selector:
    matchLabels:
      app: ms-categorie
  replicas: 4
  template:
    metadata:
      labels:
        app: ms-categorie
    spec:
      containers:
        - name: ms-categorie
          image: docker.io/hazemfelhi/ms-categorie:v5
          ports:
            - containerPort: 8070
          env:   # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address
              value: postgresql
            - name: DB_NAME  # Setting Database name
              value: categorie
            - name: DB_USERNAME  # Setting Database username
              value: postgres
            - name: DB_PASSWORD # Setting Database password
              value: root
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2