apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: ingress-nginx.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ms-categorie-service
                port:
                  number: 8070



