apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-categorie
spec:
  selector:
    matchLabels:
      app: ms-categorie
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-categorie
    spec:
      containers:
      - name: ms-categorie
        image: docker.io/hazemfelhi/ms-categorie:vv #docker.io/moohamedd/angular-app:v1 
        ports:
        - containerPort: 8087
        env:
          - name: POSTGRES_USER
            value: postgres
            # valueFrom:
            #   configMapKeyRef:
            #     name: postgres-config
            #     key: postgres_user
          - name: POSTGRES_PASSWORD
            value: password
            # valueFrom:
            #   configMapKeyRef:
            #     name: postgres-config
            #     key: postgres_password
          - name: POSTGRES_HOST
            value: jdbc:postgresql://postgresql:5432/northwind?useSSL=false
            # valueFrom:
            #   configMapKeyRef:
            #     name: hostname-config
            #     key: postgres_host
          

        # volumeMounts:
        # - name: categorie-volume
        #   mountPath: "/config"
        #   readOnly: true
