apiVersion: argoproj.io/v1alpha1
kind: Rollout #Deployment
metadata:
  name: ms-categoriee
spec:
  selector:
    matchLabels:
      app: ms-categoriee
  replicas: 4
  template:
    metadata:
      labels:
        app: ms-categoriee
    spec:
      containers:
        - name: ms-categoriee
          image: docker.io/hazemfelhi/ms-categoriee:vf
          ports:
            - containerPort: 8070
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2