apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-categorie
spec:
  selector:
    matchLabels:
      app: ms-categorie
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-categorie
    spec:
      volumes:
      - name: categorie-volume
        configMap:
          name: microservice-config
          items:
          - key: "categorie.properties"
            path: "categorie.properties"
      containers:
      - name: ms-categorie
        image: docker.io/hazemfelhi/ms-categorie:ll #docker.io/moohamedd/angular-app:v1 
        ports:
        - containerPort: 8087
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
          

        # volumeMounts:
        # - name: categorie-volume
        #   mountPath: "/config"
        #   readOnly: true
