apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-categorie
spec:
  selector:
    matchLabels:
      app: ms-categorie
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-categorie
    spec:
      # volumes:
      # - name: categorie-volume
      #   configMap:
      #     name: microservice-config
      #     items:
      #     - key: "categorie.properties"
      #       path: "categorie.properties"
      containers:
      - name: ms-categorie
        image: docker.io/hazemfelhi/ms-categorie:cf #docker.io/moohamedd/angular-app:v1 
        ports:
        - containerPort: 8087
        env:
          - name: SPRING_DATASOURCE_PASSWORD
            value: password
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://postgres-service:5432/categorie?useSSL=false
          - name: SPRING_DATASOURCE_USERNAME
            value: admin
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: update
          - name: SPRING_APPLICATION_NAME
            value: "ms-categorie"
          - name: EUREKA_SERVER_URL
            value: "http://eureka-server-service:8761"
          

        # volumeMounts:
        # - name: categorie-volume
        #   mountPath: "/config"
        #   readOnly: true
