# Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
  name: ms-categoriee-service
spec:
  ports:
    - protocol: "TCP"
      port: 8071    # Port inside the cluster
      protocol: TCP
      targetPort: 8071
  selector:
    app: ms-categoriee