apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: docker.io/hazemfelhi/postgres:v5 #docker.io/moohamedd/angular-app:v1 
        ports:
        - containerPort: 5432
